-- Active: 1670332519346@@127.0.0.1@3306
use msblog_mini;

CREATE TABLE `authors`(
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`name` VARCHAR(255) NOT NULL,
	`email` VARCHAR(255) NOT NULL UNIQUE,
	`password` VARCHAR(255) NOT NULL,
	`email_verified` BOOL DEFAULT 0,
	`profile_picture` VARCHAR(255),
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`id`)
);

CREATE TABLE `categories`(
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`title` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
	`slug` VARCHAR(255) NOT NULL UNIQUE,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE `tags`(
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`title` VARCHAR(255) NOT NULL,
	`slug` VARCHAR(255) NOT NULL UNIQUE,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE `modules`(
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`title` VARCHAR(255) NOT NULL,
    `description` TEXT NOT NULL,
	`thumbnail` VARCHAR(255) NOT NULL,
	`slug` VARCHAR(255) NOT NULL UNIQUE,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
);

CREATE TABLE `posts`(
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
    `author_id` INT,
    `module_id` INT NULLABLE,
	`title` VARCHAR(255) NOT NULL,
    `body` TEXT(500) NOT NULL,
	`thumbnail` VARCHAR(255) NOT NULL,
	`slug` VARCHAR(255) NOT NULL UNIQUE,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
    FOREIGN KEY (`author_id`) REFERENCES authors(id) ON DELETE SET NULL,
    FOREIGN KEY (`module_id`) REFERENCES modules(id) ON DELETE SET NULL
);

CREATE TABLE `category_post`(
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
    `category_id` INT,
    `post_id` INT,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
    FOREIGN KEY (`category_id`) REFERENCES categories(id) ON DELETE CASCADE,
    FOREIGN KEY (`post_id`) REFERENCES posts(id) ON DELETE CASCADE
);

CREATE TABLE `post_tag`(
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
    `post_id` INT,
    `tag_id` INT,
	`created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (id),
    FOREIGN KEY (`post_id`) REFERENCES posts(id) ON DELETE CASCADE,
    FOREIGN KEY (`tag_id`) REFERENCES tags(id) ON DELETE CASCADE
);